name: Snowflake CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Snowflake Connector
      run: pip install snowflake-connector-python snowflake-sqlalchemy

    - name: Run SQL Scripts
      env:
        SNOWFLAKE_USER: ${{ secrets.USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SCHEMA }}
      run: |
        python run_sql_scripts.py
