name: Scheduled Python Job

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Snowflake Snowpark
      run: pip install snowflake-snowpark-python

    - name: Run Python Script
      env:
        SNOWFLAKE_USER: 'your_username'  # Hardcoded username
        SNOWFLAKE_PASSWORD: 'your_password'  # Hardcoded password
        SNOWFLAKE_ACCOUNT: 'your_account'  # Hardcoded account identifier (e.g., 'xy12345')
        SNOWFLAKE_WAREHOUSE: 'your_warehouse'  # Hardcoded warehouse
        SNOWFLAKE_DATABASE: 'your_database'  # Hardcoded database
        SNOWFLAKE_SCHEMA: 'your_schema'  # Hardcoded schema
      run: python auto_execution.py
